server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://${RDS_HOST}:${RDS_PORT}/${RDS_DATABASE}
    username: ${RDS_USER}
    password: ${RDS_PASSWORD}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect