server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: orders-group
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer