spring:
  application:
    name: PRODUCT-SERVICE
  profiles:
    active:
      - ${SPRING_PROFILES_ACTIVE:h2}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always