server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product?createDatabaseIfNotExist=true
    username: root
    password: Root@123
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect